baadal/OCR_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', include("uploader.urls")),
    path('', include('g_forms.urls')),
    path('favicon.ico', RedirectView.as_view(url = staticfiles_storage.url('favicon.ico'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

baadal/g_forms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('register', views.register, name="register"),
    path('logout', views.logout_view, name="logout"),
    path('form/create', views.create_form, name="create_form"),
    path('form/<str:code>/edit', views.edit_form, name="edit_form"),
    path('form/<str:code>/edit_title', views.edit_title, name="edit_title"),
    path('form/<str:code>/edit_description', views.edit_description, name="edit_description"),
    path('form/<str:code>/edit_background_color', views.edit_bg_color, name="edit_background_color"),
    path('form/<str:code>/edit_text_color', views.edit_text_color, name="edit_text_color"),
    path('form/<str:code>/edit_setting', views.edit_setting, name="edit_setting"),
    path('form/<str:code>/delete', views.delete_form, name="delete_form"),
    path('form/<str:code>/edit_question', views.edit_question, name="edit_question"),
    path('form/<str:code>/edit_choice', views.edit_choice, name="edit_choice"),
    path('form/<str:code>/add_choice', views.add_choice, name="add_choice"),
    path('form/<str:code>/remove_choice', views.remove_choice, name="remove_choice"),
    path('form/<str:code>/get_choice/<str:question>', views.get_choice, name="get_choice"),
    path('form/<str:code>/add_question', views.add_question, name="add_question"),
    path('form/<str:code>/delete_question/<str:question>', views.delete_question, name="delete_question"),
    path('form/<str:code>/score', views.score, name="score"),
    path('form/<str:code>/edit_score', views.edit_score, name="edit_score"),
    path('form/<str:code>/answer_key', views.answer_key, name="answer_key"),
    path('form/<str:code>/feedback', views.feedback, name="feedback"),
    path('form/<str:code>/viewform', views.view_form, name="view_form"),
    path('form/<str:code>/submit', views.submit_form, name="submit_form"),
    path('403', views.FourZeroThree, name="403"),
    path('404', views.FourZeroFour, name="404")
]

baadal/uploader/models.py
from django.db import models
from core import utils
import hashlib
from PIL import Image
import pytesseract


class ImageFileManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(models.Q(internal_reference__icontains=query) |
                                          models.Q(name__icontains=query) |
                                          models.Q(description__icontains=query)
                                          )


class ImageFile(models.Model):
    #import pymongo
    #myclient=pymongo.MongoClient("mongodb://localhost:27017")
    #mydb=myclient["baadal"]
    #n=mydb['g_forms_form']
    #l={} 
    #for i in n.find():
     #   l[i['id']]=i['title']
    #l1=tuple((l.items()))
    #application = models.CharField(max_length=6, choices=l1, default='')
    #name = models.CharField("Name", max_length=100)
    internal_reference = models.CharField("Internal Reference", max_length=100, editable=False)
    description = models.TextField("Description", blank=True, null=True)
    image = models.ImageField(upload_to="OCR_image/input/", verbose_name="Input Image")
    create_at = models.DateTimeField("Create at", auto_now_add=True)
    updated_at = models.DateTimeField("Update at", auto_now=True)
    def __str__(self):
        return "{0:03d} - {1}".format(self.id, self.image)

    def execute_and_save_ocr(self):
        import time
        start_time = time.time()
        img = Image.open(self.image)
        txt = pytesseract.image_to_string(img, lang='eng')
        execution_time = time.time() - start_time
        ocr_txt = OCRText(image = self, text = txt, lang = "EN", execution_time = execution_time)
        ocr_txt.save()

        print("The image {0} was opened.".format(self.image))
        print('OCR: \n{0}\n'.format(txt))
        print('Execution Time: {0}'.format(ocr_txt.execution_time))

        return ocr_txt

    """
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('course_details', args=[], kwargs={'slug': self.slug})
    """

    def save(self, *args, **kwargs):

        if not self.internal_reference:
            random_value = utils.random_value_generator(size=20)
            while ImageFile.objects.filter(internal_reference=random_value).exists():
                random_value = utils.random_value_generator(size=20)
            hash_value = hashlib.md5(bytes(str(self.id) + str(random_value), 'utf-8'))
            self.internal_reference = hash_value.hexdigest()
        super(ImageFile, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "ImageFile"
        verbose_name_plural = "ImageFiles"
        ordering = ['id']

    objects = ImageFileManager()


class OCRText(models.Model):
    text = models.TextField("OCR text", blank=True)
    lang = models.TextField("Language", default="EN")
    execution_time = models.IntegerField("Execution Time", editable=False, null=True);
    image = models.ForeignKey('ImageFile', on_delete=models.CASCADE)
    create_at = models.DateTimeField("Create at", auto_now_add=True)
    updated_at = models.DateTimeField("Update at", auto_now=True)

    def __str__(self):
        return "{0:03d} - {1}".format(self.id, self.image.internal_reference)

    class Meta:
        verbose_name = "OCRText"
        verbose_name_plural = "OCRTexts"
        ordering = ['id']

baadal/g_forms/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.db import IntegrityError
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from .models import User, Choices, Questions, Answer, Form, Responses
from django.core import serializers
import json
import random
import string

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    forms = Form.objects.filter(creator = request.user)
    return render(request, "g_forms/index.html", {
        "forms": forms
    })

def login_view(request):
    #Check if the user is logged in
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('index'))
    if request.method == "POST":
        username = request.POST["username"].lower()
        password = request.POST["password"]
        user = authenticate(request, username = username, password = password)
        # if user authentication success
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, "g_forms/login.html", {
                "message": "Invalid username and/or password"
            })
    return render(request, "g_forms/login.html")

def register(request):
    #Check if the user is logged in
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('index'))
    if request.method == "POST":
        username = request.POST["username"].lower()
        password = request.POST["password"]
        email = request.POST["email"]
        confirmation = request.POST["confirmation"]
        #check if the password is the same as confirmation
        if password != confirmation:
            return render(request, "g_forms/register.html", {
                "message": "Passwords must match."
            })
        #Checks if the username is already in use
        if User.objects.filter(email = email).count() == 1:
            return render(request, "g_forms/register.html", {
                "message": "Email already taken."
            })
        try:
            user = User.objects.create_user(username = username, password = password, email = email)
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        except IntegrityError:
            return render(request, "g_forms/register.html", {
                "message": "Username already taken"
            })
    return render(request, "g_forms/register.html")


def logout_view(request):
    #Logout the user
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def create_form(request):
    # Creator must be authenticated
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    # Create a blank form API
    if request.method == "POST":
        data = json.loads(request.body)
        title = data["title"]
        code = ''.join(random.choice(string.ascii_letters + string.digits) for x in range(30))
        choices = Choices(choice = "Option 1")
        choices.save()
        question = Questions(question_type = "multiple choice", question= "Untitled Question", required= False)
        question.save()
        question.choices.add(choices)
        question.save()
        form = Form(code = code, title = title, creator=request.user)
        form.save()
        form.questions.add(question)
        form.save()
        return JsonResponse({"message": "Sucess", "code": code})

def edit_form(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse("404"))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    return render(request, "g_forms/form.html", {
        "code": code,
        "form": formInfo
    })

def edit_title(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse("404"))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    if request.method == "POST":
        data = json.loads(request.body)
        if len(data["title"]) > 0:
            formInfo.title = data["title"]
            formInfo.save()
        else:
            formInfo.title = formInfo.title[0]
            formInfo.save()
        return JsonResponse({"message": "Success", "title": formInfo.title})

def edit_description(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse("404"))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    if request.method == "POST":
        data = json.loads(request.body)
        formInfo.description = data["description"]
        formInfo.save()
        return JsonResponse({"message": "Success", "description": formInfo.description})

def edit_bg_color(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse("404"))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    if request.method == "POST":
        data = json.loads(request.body)
        formInfo.background_color = data["bgColor"]
        formInfo.save()
        return JsonResponse({"message": "Success", "bgColor": formInfo.background_color})

def edit_text_color(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse("404"))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    if request.method == "POST":
        data = json.loads(request.body)
        formInfo.text_color = data["textColor"]
        formInfo.save()
        return JsonResponse({"message": "Success", "textColor": formInfo.text_color})

def edit_setting(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse("404"))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    if request.method == "POST":
        data = json.loads(request.body)
        formInfo.collect_email = data["collect_email"]
        formInfo.is_quiz = data["is_quiz"]
        formInfo.authenticated_responder = data["authenticated_responder"]
        formInfo.confirmation_message = data["confirmation_message"]
        formInfo.edit_after_submit = data["edit_after_submit"]
        formInfo.allow_view_score = data["allow_view_score"]
        formInfo.save()
        return JsonResponse({'message': "Success"})

def delete_form(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse("404"))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    if request.method == "DELETE":
        #Delete all questions and choices
        for i in formInfo.questions.all():
            for j in i.choices.all():
                j.delete()
            i.delete()
        for i in Responses.objects.filter(response_to = formInfo):
            for j in i.response.all():
                j.delete()
            i.delete()
        formInfo.delete()
        return JsonResponse({'message': "Success"})

def edit_question(request, code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    formInfo = Form.objects.filter(code = code)
    #Checking if form exists
    if formInfo.count() == 0:
        return HttpResponseRedirect(reverse('404'))
    else: formInfo = formInfo[0]
    #Checking if form creator is user
    if formInfo.creator != request.user:
        return HttpResponseRedirect(reverse("403"))
    if request.method == "POST":
        data = json.loads(request.body)
        question_id = data["id"]
        question = Questions.objects.filter(id = question_id)
        if question.count() == 0:
            return HttpResponseRedirect(reverse("404"))
        else: question = question[0]
        question.question = data["question"]
        question.question_type = data["question_type"]
        question.required = data["required"]
        if(data.get("score")): question.score = data["score"]
        if(data.get("answer_key")): question.answer_key = data["answer_key"]
        question.save()

baadal/g_forms/templates/g_forms/edit_response.html
{% extends 'g_forms/layout.html' %}
{% load static %}
{% load get_response %}
{% load to_int %}
{% load is_response %}
{% block title %}{{form.title}} ~ Baadal Forms{% endblock %}
{% block script %}
<script src="{% static 'index/viewform.js' %}" defer></script>
{% endblock %}
{% block body %}
<div class="container-fluid">
    <form class="container" method="POST" action="{% url 'edit_response' form.code response.response_code %}"
        autocomplete="off">
        <span id="bg-color" style="display: none;">{{form.background_color}}</span>
        <span id="text-color" style="display: none;">{{form.text_color}}</span>
        {% csrf_token %}
        <div class="margin-top-bottom box question-box">
            <div class="form-title-box">
                <h1 class="form-title txtClr">{{form.title}}</h1>
                <p class="required-info">* Required</p>
            </div>
            <div class="form-description txtClr">{{form.description|linebreaksbr}}</div>
        </div>
        {% if form.collect_email %}
        <div class="margin-top-bottom box question-box">
            <h1 class="question-title txtClr">Email address: <span class="require-star">*</span></h1>
            <input type="email" name="email-address" class="short-answer" required
                value="{{response.responder_email}}">
        </div>
        {% endif %}
        {% for question in form.questions.all %}
        <div class="margin-top-bottom box question-box">
            {% if form.is_quiz %}
            <h1 class="question-title txtClr">{{question.question}} {% if question.required %}<span
                    class="require-star">*</span>{% endif %}</h1>
            {% else %}
            <h1 class="question-title txtClr" oncopy="return false">{{question.question}} {% if question.required
                %}<span class="require-star">*</span>{% endif %}</h1>
            {% endif %}
            {% if question.question_type == "short" %}
            <input type="text" name="{{question.id}}" class="short-answer" {% if
                question.required %} required {% endif %} value="{{response|get_response:question.pk}}">
            {% elif question.question_type == "paragraph" %}
            <textarea name="{{question.id}}" class="long-answer textarea-adjust" {% if
                question.required %} required {% endif %}>{{response|get_response:question.pk}}</textarea>
            {% elif question.question_type == "multiple choice" %}
            {% for choice in question.choices.all %}
            <div class="multiple-choice">
                {% if response|get_response:question.pk|to_int == choice.pk|to_int %}
                <input type="radio" name="{{question.id}}" id="{{choice.id}}" {% if question.required %} required {%
                    endif %} value="{{choice.id}}" checked>
                {% else %}
                <input type="radio" name="{{question.id}}" id="{{choice.id}}" {% if question.required %} required {%
                    endif %} value="{{choice.id}}">
                {% endif %}
                <label for="{{choice.id}}" class="txtClr">{{choice.choice}}</label>
            </div>
            {% endfor %}
            {% elif question.question_type == "checkbox" %}
            {% for choice in question.choices.all %}
            <div class="multiple-choice">
                {% if response|get_responses:question.pk|is_response:choice.pk %}
                <input type="checkbox" name="{{question.id}}" id="{{choice.id}}" {% if question.required %} required {%
                    endif %} value="{{choice.id}}" checked>
                {% else %}
                <input type="checkbox" name="{{question.id}}" id="{{choice.id}}" {% if question.required %} required {%
                    endif %} value="{{choice.id}}">
                {% endif %}
                <label for="{{choice.id}}" class="txtClr">{{choice.choice}}</label>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        
    </form>
    {% if user == form.creator %}
    <a href="{% url 'edit_form' form.code %}">
        <img src="{% static 'Icon/question.png' %}" alt="Edit Question" title="Edit this form" class="edit-form-link">
    </a>
    {% endif %}
</div>
{% endblock %}

baadal/g_forms/templates/g_forms/form_response.html
{% extends 'g_forms/layout.html' %}
{% load static %}
{% block script %}
<script src="{% static 'index/viewform.js' %}" defer></script>
{% endblock %}
{% block body %}
<br><br><br>
<div class="container">
    <span id="bg-color" style="display: none;">{{form.background_color}}</span>
    <span id="text-color" style="display: none;">{{form.text_color}}</span>
    <div class="margin-top-bottom box box-shadow bg-white">
        <h1 class="form-title txtClr">{{form.title}}</h1>
        <p class="text-label margin-left-right" style="margin-left: 10px;">{{form.confirmation_message}}</p>
        {% if form.edit_after_submit %}
        <a href="{% url 'edit_response' form.code code %}" class="edit-response-link">Edit response</a>
        {% endif %}
        {% if form.is_quiz and form.allow_view_score %}
        <div class="modal-division">
            <!--<a href="{% url 'response' form.code code %}" class="btn view-score-btn">View Score</a>--->
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

baadal/g_forms/templates/g_forms/index.html
{% extends 'g_forms/layout.html' %}
{% load static %}

{% block body %}
<div class="create-form">
    <div class="container">
        <p class="forms-label">Start a new form</p>
        <div class="form-template-box">
            <img src="{% static 'Icon/blank-form.png' %}" alt="Blank form" title="Blank form"
                id="create-blank-form">
            <span class="form-template-label">Blank Form</span>
        </div>
    </div>
</div>
<div class="container">
    <div class="form-list">
        <p class="forms-label">Your forms:</p>
        {% for i in forms %}
        <a href="{% url 'edit_form' i.code %}" class="form-list-link">
            <div class="form-box">
                <div class="form-list-title">
                    <h5 class="form-list-title-text">{{i.title}}</h5>
                </div>
                {% if i.createdAt == i.updatedAt %}
                <p class="form-list-timestamp">{{i.createdAt}}</p>
                {% else %}
                <p class="form-list-timestamp">{{i.updatedAt}}</p>
                {% endif %}
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

baadal/g_forms/templates/g_forms/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Baadal Forms{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'index/HurlUI.css' %}">
    <link rel="stylesheet" href="{% static 'index/style.css' %}">
    
    <script src = "{% static 'index/index.js' %}" defer></script>
    <script src="{% static 'lib/cookie.min.js' %}" defer></script>

    <script src="{% static 'index/form.js' %}"></script>

    <script src="{% static 'index/viewform.js' %}" defer></script>
    {% block script %}
    {% endblock %}
</head>

<body>
    <div class="container-fluid">
        <div class="topnav nav-effect" style="margin-bottom: 20px;">
            <div class="nav-padding">
                <span class="nav-ham" id="nav-ham">&#9776;</span>
                <a href = "/">
                    <img src="{% static 'Icon/icon2.png' %}" alt="Baadal Forms Icon" class="navbar-icon form-icon" title="Forms">
                </a>
                <span class="nav-text" title="Forms"><a href="{% url 'index' %}" class="nav-link">Baadal
                        Forms</a></span>
                <a href="{% url 'logout' %}">
                    <img src="{% static 'Icon/Logout.jpg' %}" alt="Logout Icon"
                        class="navbar-icon float-right logout-icon" title="Logout">
                </a>
            </div>
        </div>
        <div class="sidebar" id="sidebar">
            <span class="close-sidebar" id="close-sidebar">&times;</span>
            <div class="sidebar-content">
                <h4 class="sidebar-title">
                    <a href="{% url 'index' %}" class="sidebar-title-link">
                        <span>Baadal Forms</span>
                    </a>
                </h4>
                
            </div>
        </div>
    </div>

    {% block body %}
    {% endblock %}

</body>

</html>

baadal/g_forms/templates/g_forms/login.html
{% extends 'g_forms/layout.html' %}

{% block body %}
<div class="create-form">
    <div class="container">    
        <form class="box box-shadow margin-top-bottom" method="POST" action = "{% url 'login' %}" style="margin-left: 250px; margin-right: 250px;">
            <div class="form-group">
                <h1 class="box-title">Login user</h1>
                <p class="form-error">{{message}}</p>
                {% csrf_token %}
            </div>
            <div class="form-group">
                <p class="form-label">Username:</p>
                <input type="text" class="form-control" name="username">
            </div>
            <div class="form-group">
                <p class="form-label">Password:</p>
                <input type="password" name="password" class="form-control">
            </div>
            <div class="form-group">
                <p class="form-label">Don't have account yet? <a class="link" href = "{% url 'register' %}">Register</a></p>
                <input type="submit" value="Login" class="btn btn-dark form-control">
            </div>
        </form>
    </div>
</div>
{% endblock %}

baadal/g_forms/templates/g_forms/main.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block extrahead %} {% endblock %}

{% block extrastyle %}
<style>

    .clickable_img:hover {
        cursor: pointer;
    }
</style>

{% endblock %}

{% block extrascript %}
<script>
$('.custom-file-input').on('change', function() {
   let fileName = $(this).val().split('\\').pop();
   $(this).next('.custom-file-label').addClass("selected").html(fileName);
});


function show_img_details(img_path){
    $('#img_detail').attr("src", img_path);
    $('#img_detail_modal').modal('toggle');
}


</script>

{% endblock %}


{% block content %}

<div class="mt-5 text-center">
    <h1>Baadal upload</h1>
</div>
<div class="offset-md-2 col-md-8 my-5" id="image_form">
    <form action="#image_form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ image_form.application }}
        <fieldset class="form-group">
            <div class="custom-file my-2">
                {{image_form.image|add_class:"custom-file-input"}}
                <label class="custom-file-label">{{ image_form.image.label }}</label>
                {% for error in field.errors %}
                <span class="badge badge-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </fieldset>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col" class="text-center">#</th>
            <th scope="col" class="d-none d-sm-table-cell">Internal Reference</th>
            <th scope="col" class="d-none d-md-table-cell">Text image</th>
            <th scope="col" class="text-center">Image</th>
        </tr>
        </thead>
        <tbody>
        {% for image in image_list %}
        <tr>
            <th scope="row">{{image.id}}</th>
            <td class="d-none d-sm-table-cell">{{image.internal_reference}}</td>
            {% with image.ocrtext_set.last as ocrtext%}
            <td class="d-none d-md-table-cell">{{ ocrtext.text|truncatechars:350}}</td>
            {% endwith%}
            <td class="text-center">
                <div class="clickable_img"  onclick="show_img_details('/media/{{image.image}}')">
                    <img class="img-fluid img-thumbnail " src="/media/{{image.image}}" alt="{{image.image}}" width="100" />
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


<div id="img_detail_modal" class="modal mt-5" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="img_detail" class="img-fluid" src="" alt="" />
            </div>
        </div>
    </div>
</div>


{% endblock %}

baadal/g_forms/templates/g_forms/register.html
{% extends 'g_forms/layout.html' %}
{% block body %}
<div class="create-form">
    <div class="container">
        <form action="{% url 'register' %}" method="post" class="box box-shadow margin-top-bottom"
            style="margin-left: 250px; margin-right: 250px;">
            <div class="form-group">
                <h1 class="box-title">Register user</h1>
                <p class="form-error">{{message}}</p>
                {% csrf_token %}
            </div>
            <div class="form-group">
                <p class="form-label">Username:</p>
                <input type="text" class="form-control" name="username">
            </div>
            <div class="form-group">
                <p class="form-label">Email:</p>
                <input type="email" name="email" class="form-control">
            </div>
            <div class="form-group">
                <p class="form-label">Password:</p>
                <input type="password" name="password" class="form-control">
            </div>
            <div class="form-group">
                <p class="form-label">Password Confirmation:</p>
                <input type="password" name="confirmation" class="form-control">
            </div>
            <div class="form-group">
                <p class="form-label">Already have account? <a class="link" href="{% url 'login' %}">Login</a></p>
                <input type="submit" value="Register" class="btn btn-dark form-control">
            </div>
        </form>
    </div>
</div>
{% endblock %}